site_name: Friendly Feedback Knowledge Base
theme: slate
extra_css:
  - style.css
nav:
  - Home: 'index.md'
  - Industry: 'industry.md'
  - Fundamentals: 'fundamentals/game_art_fundamentals.md'
  - Disciplines: 'disciplines.md'
  - Software: 'software.md'
  - About: 'about.md'
plugins:
    - mkdocs-video