site_name: Friendly Feedback Knowledge Base
theme: slate
extra_css:
  - style.css
nav:
  - Home: 'index.md'
  - About: 'About.md'
  - Industry: 'Industry.md'
  - Fundamentals: 'Fundamentals.md'
  - Disciplines: 'Disciplines.md'
  - Software: 'Software.md'
plugins:
    - mkdocs-video