site_name: Friendly Feedback Knowledge Base
theme: slate
extra_css:
  - css/style.css
  - css/link-embeds.css
nav:
  - Home: 'index.md'
  - Industry: 'industry.md'
  - Fundamentals: 'fundamentals/game_art_fundamentals.md'
  - Disciplines: 'disciplines.md'
  - Software: 'software.md'
  - About: 'about.md'
plugins:
    - mkdocs-video
    - link-embeds:
        enabled: true
        name_default: "Untitled Link"
        desc_default: "No description found"
        image_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/c0298d98-0910-4235-a88f-0c3e2f704ba7"
        image_disabled: false
        favicon_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/13a151b1-d7f9-4e27-909b-a26986ab0954"
        favicon_disabled: false
        favicon_size: 25
        target: "blank"
        accent: "FFFFFF1A"
        verbose: false