site_name: Friendly Feedback Knowledge Base

# CSS style sheets
extra_css:
  - css/link-embeds.css
  - css/style.css

# Material theme settings
theme:
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  logo:
    img/friendly_feedback_icon_02.png
  favicon:
    img/friendly_feedback_icon_01.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# Extra schtuff
extra:
  # Footer icon links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Zalek4/Friendly-Feedback-Knowledge-Base/tree/main
    - icon: fontawesome/brands/discord
      link: https://discord.gg/UatB2ChxPg

# Navigation for site
nav:
  - Home: 'index.md'
  - Industry: 'industry.md'
  - Fundamentals: 'fundamentals/game_art_fundamentals.md'
  - Disciplines: 'disciplines.md'
  - Software: 'software.md'
  - About: 'about.md'
  - Formatting: 'formatting.md'

# Plugins
plugins:
    - search
    - mkdocs-video
    - link-embeds:
        enabled: true
        name_default: "Untitled Link"
        desc_default: "No description found"
        image_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/c0298d98-0910-4235-a88f-0c3e2f704ba7"
        image_disabled: false
        favicon_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/13a151b1-d7f9-4e27-909b-a26986ab0954"
        favicon_disabled: false
        favicon_size: 25
        target: "blank"
        accent: "FFFFFF1A"
        verbose: false

# Markdown specific extensions
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.b64
  - pymdownx.betterem
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.tab
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.escapeall
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.pathconverter
  - pymdownx.progressbar
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.striphtml
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde